-- Add journaling storage for daily reflections and backfill a required
-- Reflection task on every plan day.

create table if not exists public.user_reflection_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  plan_day_id bigint not null references public.plan_days (id) on delete cascade,
  challenge_day_number integer not null,
  prompt_text text,
  entry_text text not null check (btrim(entry_text) <> ''),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, plan_day_id)
);

alter table public.user_reflection_entries enable row level security;

drop policy if exists "Users can read their own reflection entries"
  on public.user_reflection_entries;
create policy "Users can read their own reflection entries"
  on public.user_reflection_entries
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own reflection entries"
  on public.user_reflection_entries;
create policy "Users can insert their own reflection entries"
  on public.user_reflection_entries
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own reflection entries"
  on public.user_reflection_entries;
create policy "Users can update their own reflection entries"
  on public.user_reflection_entries
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own reflection entries"
  on public.user_reflection_entries;
create policy "Users can delete their own reflection entries"
  on public.user_reflection_entries
  for delete
  using (auth.uid() = user_id);

insert into public.task_templates (slug, title, description, cadence, weekly_target)
values (
  'reflection',
  'Reflection',
  'Write and save your daily reflection before marking this complete.',
  'daily',
  null
)
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  cadence = excluded.cadence,
  weekly_target = excluded.weekly_target;

insert into public.plan_day_tasks (plan_day_id, task_template_id, is_required, sort_order)
select
  pd.id,
  tt.id,
  true,
  999
from public.plan_days pd
cross join (
  select id
  from public.task_templates
  where slug = 'reflection'
  limit 1
) tt
where not exists (
  select 1
  from public.plan_day_tasks pdt
  where pdt.plan_day_id = pd.id
    and pdt.task_template_id = tt.id
);
